### ISSUE TITLE
Does not Join vc , When Comes Online again

### ISSUE THREAD

**Issue by Just-Msv** [Weeb-Devs/Laffey#13]
- When The bot went offline when it has 24/7 cmd on , if the bot is came online it not coming to the same vc , can u see this issue pls

**Comment by Takiyo0** [comment]
24/7 at the moment means the bot won't leave when there's no user inside VC. It won't join VC again after offline. I will make an update for the bot to auto rejoin VC after offline. This may take a bit of time so stay tuned :)

**Comment by Just-Msv** [comment]
thnx for that

**Comment by Takiyo0** [comment]
added the auto-resume feature. enjoy!
