### ISSUE TITLE
commands Update

### ISSUE THREAD

**Issue by rajamoulimallareddy** [Weeb-Devs/Laffey#23]
It's better to Rename and change Play to Search And ForcePlay to play

**Comment by Takiyo0** [comment]
forceplay and play are different since forceplay will directly play the song that has been requested and play doesn't. And for play and search, I will start working on them and will make a pull request as fast as possible with other changes.

**Comment by rajamoulimallareddy** [comment]
> forceplay and play are different since forceplay will directly play the song that has been requested and play doesn't. And for play and search, I will start working on them and will make a pull request as fast as possible with other changes.
