### ISSUE TITLE
KSoft Lyrics Don't Work!

### ISSUE THREAD

**Issue by apidev234** [Weeb-Devs/Laffey#29]
I Have a KSoft API Key. I Tried Running The Bot It Works Fine!

I Tried the lyrics command and it says No lyrics found everytime.

Please upgrade to genius-lyrics-api
Its better than ksoft.

**Comment by Takiyo0** [comment]
can you try to add `console.log(x)` inside this catch statement? https://github.com/Weeb-Devs/Laffey/blob/31f931abff7f682fe88baebcff5d6369f35cb334/src/commands/music/lyrics.js#L24

**Comment by Takiyo0** [comment]
made a pull request https://github.com/Weeb-Devs/Laffey/pull/30 so you have 3 lyrics engine options
ksoft, genius, and google
