### ISSUE TITLE
Hello can you make a autoconnect feature?

### ISSUE THREAD

**Issue by iamnoob6969** [Weeb-Devs/Laffey#35]
For example when a bot goes offline with 24/7 enabled when it goes back online it would auto connect to the specific voice channel where it left.

**Comment by Takiyo0** [comment]
Hi, the bot already has that feature. No matter if you enabled or disabled the 24/7 mode, it'll automatically resume all players after you're turning on the bot from downtime. Make sure you have MONGODB_URI sets in either config.json / .env
If everything is good, you will see the `found <total players> queue. Resuming all queue` text on the log like this
![WindowsTerminal_WzPIaQaCMr](https://user-images.githubusercontent.com/60313514/135620102-edd58f36-a630-4c75-a701-eaeda2cf910b.png)

**Comment by dslvd** [comment]
Okay thanks!

**Comment by dslvd** [comment]
oops wrong repo
