### ISSUE TITLE
Increase Spotify Album/Playlist limit

### ISSUE THREAD

**Issue by getxd-dev** [Weeb-Devs/Laffey#36]
Is there a way to increase Spotify Album/Playlist limit, cuz it only plays first page which is the first 100 songs.

**Comment by Takiyo0** [comment]
> 
> 
> For some reason it doesn't work for me, still plays first page (first 100 songs). Maybe is it because I'm using [better-erela.js-spotify](https://www.npmjs.com/package/better-erela.js-spotify)?

yes since it's a different module, we're using `erela.js-spotify` and not `better-erela.js-spotify`
