### ISSUE TITLE
lyric not working

### ISSUE THREAD

**Issue by fenismonjaa** [Weeb-Devs/Laffey#55]
**Describe the bug**
i already change lyric engine to 'google' or 'genius', but bot still asking for ksoft api when using **?lyrics** command

**Comment by Takiyo0** [comment]
hello, can you give me the full error? is it asking the ksoft api key through error or the bot reply?

**Comment by fenismonjaa** [comment]
> hello, can you give me the full error? is it asking the ksoft api key through error or the bot reply?

yes, bot always asking for ksoft api which mean, another engine didnt work

**Comment by Takiyo0** [comment]
fixed, you may want to check it right now, feel free to re-open this issue if still not fixed or appear another error

**Comment by fenismonjaa** [comment]
key thanks
